
//  * Gantt chart activities per project.
//  * Image upload is handled here: the file must already be registered in the Files
//  * collection (uploaded via presigned URL flow) before it can be attached to an activity.
//  *
//  * Security:
//  *  - All operations always scoped to tenantId + projectId
//  *  - CLIENT_TEMP users can read (via project scope check in routes)
//  *  - Image upload allowed for PM, Admin, and Member roles
//  *  - Status changes auto-generate a CalendarEvent
 

const activityRepo  = require('./activity.repository');
const projectRepo   = require('../projects/project.repository');
const CalendarEvent = require('../calendar/calendarEvent.model');
const File          = require('../files/file.model');
const { FILE_CATEGORIES } = require('../../constants/fileCategories');

const _assertProject = async (tenantId, projectId) => {
  const project = await projectRepo.findByIdLean(projectId, tenantId);
  if (!project) throw Object.assign(new Error('Project not found'), { status: 404 });
  return project;
};

const listActivities = async (tenant, projectId) => {
  await _assertProject(tenant._id, projectId);
  const activities = await activityRepo.findByProject(tenant._id, projectId);

  // Attach imageCount to each activity 
  return activities.map((a) => ({
    ...a.toObject(),
    imageCount:    a.supportingImages.length,
    missingImages: a.status === 'complete' && a.supportingImages.length === 0,
  }));
};

const createActivity = async (tenant, projectId, data, _createdBy) => {
  await _assertProject(tenant._id, projectId);
  return activityRepo.create({ ...data, tenantId: tenant._id, projectId });
};

const updateActivity = async (tenant, projectId, activityId, updates, updatedBy) => {
  const existing = await activityRepo.findById(activityId, tenant._id, projectId);
  if (!existing) throw Object.assign(new Error('Activity not found'), { status: 404 });

  const updated = await activityRepo.updateById(activityId, tenant._id, projectId, {
    ...updates,
    lastUpdated: new Date(),
  });

  // Auto-generate CalendarEvent when status changes
  if (updates.status && updates.status !== existing.status) {
    await CalendarEvent.create({
      tenantId:      tenant._id,
      projectId,
      title:         `Activity ${updates.status}: ${existing.name}`,
      eventType:     'activity_update',
      date:          new Date(),
      allDay:        true,
      linkedEntity:  { type: 'activity', id: activityId },
      createdBy:     updatedBy,
      autoGenerated: true,
    });
  }

  return updated;
};

const deleteActivity = async (tenant, projectId, activityId) => {
  const activity = await activityRepo.findById(activityId, tenant._id, projectId);
  if (!activity) throw Object.assign(new Error('Activity not found'), { status: 404 });
  await activityRepo.deleteById(activityId, tenant._id, projectId);
  return { deleted: true };
};

//  Supporting images 


//  * Attach an already-uploaded file to an activity as a supporting image.
//  * The file must exist in the Files collection and belong to this tenant/project.
 
const addImage = async (tenant, projectId, activityId, fileId, caption, uploadedBy) => {
  const activity = await activityRepo.findById(activityId, tenant._id, projectId);
  if (!activity) throw Object.assign(new Error('Activity not found'), { status: 404 });

  // Verify the file exists and belongs to this tenant/project
  const file = await File.findOne({
    _id:       fileId,
    tenantId:  tenant._id,
    projectId,
    deletedAt: null,
  });
  if (!file) throw Object.assign(new Error('File not found for this project'), { status: 404 });

  // Ensure file is category activity-image
  if (file.category !== FILE_CATEGORIES.ACTIVITY_IMAGE) {
    // Auto-update the category to activity-image if it wasn't set correctly
    await File.findByIdAndUpdate(fileId, { category: FILE_CATEGORIES.ACTIVITY_IMAGE });
  }

  const updated = await activityRepo.addImage(activityId, tenant._id, projectId, {
    fileId,
    uploadedBy,
    caption: caption || null,
  });

  return updated;
};

const removeImage = async (tenant, projectId, activityId, imageId) => {
  const activity = await activityRepo.findById(activityId, tenant._id, projectId);
  if (!activity) throw Object.assign(new Error('Activity not found'), { status: 404 });

  const imageExists = activity.supportingImages.some(
    (img) => img._id.toString() === imageId
  );
  if (!imageExists) throw Object.assign(new Error('Image not found on this activity'), { status: 404 });

  return activityRepo.removeImage(activityId, tenant._id, projectId, imageId);
};

module.exports = {
  listActivities,
  createActivity,
  updateActivity,
  deleteActivity,
  addImage,
  removeImage,
};