// Calendar API – mocked for MVP frontend work.
// Swap implementation to use apiClient when backend is ready.
import type { CalendarEvent, CalendarEventType } from '@/types';

export interface CalendarEventsResponse {
  events: CalendarEvent[];
}

export async function fetchCalendarEvents(params?: {
  view?: 'month' | 'week' | 'list';
  date?: string;
  eventType?: CalendarEventType | null;
}): Promise<CalendarEventsResponse> {
  const baseDate = (params?.date as string | undefined) ?? new Date().toISOString().split('T')[0];

  const mockEvents: CalendarEvent[] = [
    {
      id: 'evt-1',
      tenantId: 'mock-tenant',
      projectId: 'proj-1',
      title: 'Stage 3 Complete · Mokopane WTW',
      eventType: 'milestone',
      date: baseDate,
      allDay: true,
      linkedEntity: { type: 'project', id: 'proj-1' },
      autoGenerated: true,
      createdAt: baseDate,
    },
    {
      id: 'evt-2',
      tenantId: 'mock-tenant',
      projectId: 'proj-2',
      title: 'Payment Certificate · R573 Phase 2',
      eventType: 'payment',
      date: baseDate,
      allDay: false,
      linkedEntity: { type: 'project', id: 'proj-2' },
      autoGenerated: true,
      createdAt: baseDate,
    },
    {
      id: 'evt-3',
      tenantId: 'mock-tenant',
      projectId: 'proj-3',
      title: 'Site Visit · Tzaneen Bridge',
      eventType: 'site_visit',
      date: baseDate,
      allDay: false,
      linkedEntity: { type: 'project', id: 'proj-3' },
      autoGenerated: false,
      createdAt: baseDate,
    },
  ];

  // Very light mock: ignore view/filter for now, but keep shape correct.
  return Promise.resolve({ events: mockEvents });
}

