const mongoose = require('mongoose');

const EVENT_TYPES = [
  'milestone', 'payment', 'site_visit', 'report_due',
  'meeting', 'deadline', 'stage_advanced', 'document_approved',
  'document_rejected', 'variation_approved', 'project_complete',
];

const calendarEventSchema = new mongoose.Schema(
  {
    tenantId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Tenant',
      required: true,
    },
    projectId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Project',
      default: null,
    },
    deptId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Department',
      default: null,
    },
    title: {
      type: String,
      required: true,
      trim: true,
    },
    eventType: {
      type: String,
      enum: EVENT_TYPES,
      required: true,
    },
    date: {
      type: Date,
      required: true,
    },
    endDate: {
      type: Date,
      default: null,
    },
    allDay: {
      type: Boolean,
      default: true,
    },
    linkedEntity: {
      type: { type: String, default: null },
      id: { type: mongoose.Schema.Types.ObjectId, default: null },
    },
    notes: {
      type: String,
      default: null,
    },
    autoGenerated: {
      type: Boolean,
      default: false,
    },
    createdBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'User',
      default: null,
    },
  },
  { timestamps: true }
);

calendarEventSchema.index({ tenantId: 1, date: 1 });
calendarEventSchema.index({ tenantId: 1, projectId: 1 });
calendarEventSchema.index({ tenantId: 1, eventType: 1 });

calendarEventSchema.statics.createStageEvent = async function (tenantId, projectId, stage, advancedBy) {
  return this.create({
    tenantId,
    projectId,
    title: `Stage ${stage} documents approved — project advanced`,
    eventType: 'stage_advanced',
    date: new Date(),
    autoGenerated: true,
    linkedEntity: { type: 'Project', id: projectId },
    createdBy: advancedBy,
  });
};

calendarEventSchema.statics.createPaymentEvent = async function (tenantId, projectId, paymentDate, amount, recordedBy) {
  return this.create({
    tenantId,
    projectId,
    title: `Payment recorded: R${(amount / 100).toLocaleString()}`,
    eventType: 'payment',
    date: paymentDate,
    autoGenerated: true,
    linkedEntity: { type: 'Payment', id: projectId },
    createdBy: recordedBy,
  });
};

calendarEventSchema.statics.createApprovalEvent = async function (tenantId, projectId, approved, documentCategory, reviewedBy) {
  return this.create({
    tenantId,
    projectId,
    title: `${documentCategory} ${approved ? 'approved' : 'rejected'} by client`,
    eventType: approved ? 'document_approved' : 'document_rejected',
    date: new Date(),
    autoGenerated: true,
    linkedEntity: { type: 'File', id: projectId },
    createdBy: reviewedBy,
  });
};

calendarEventSchema.statics.createVariationEvent = async function (tenantId, projectId, voNumber, reviewedBy) {
  return this.create({
    tenantId,
    projectId,
    title: `Variation Order ${voNumber} approved`,
    eventType: 'variation_approved',
    date: new Date(),
    autoGenerated: true,
    linkedEntity: { type: 'VariationOrder', id: projectId },
    createdBy: reviewedBy,
  });
};

const CalendarEvent = mongoose.model('CalendarEvent', calendarEventSchema);

module.exports = CalendarEvent;
