const FILE_CATEGORIES = {
  SCOPING_REPORT: 'scoping-report',
  APPOINTMENT_LETTER: 'appointment-letter',
  ADVERT: 'advert',
  RECOMMENDATIONS: 'recommendations',
  APPROVAL_RECORD: 'approval-record',
  SLA: 'sla',
  QUOTATION: 'quotation',
  PRELIMINARY_DESIGN: 'preliminary-design',
  PRELIMINARY_COST_ESTIMATE: 'preliminary-cost-estimate',
  PRELIMINARY_DESIGN_REPORT: 'preliminary-design-report',
  DETAILED_DESIGN: 'detailed-design',
  DETAILED_COST_ESTIMATE: 'detailed-cost-estimate',
  DETAILED_DESIGN_REPORT: 'detailed-design-report',
  TENDER_DRAWING: 'tender-drawing',
  TENDER_DOCUMENT: 'tender-document',
  TENDER_EVALUATION: 'tender-evaluation',
  PRE_EVALUATION_REPORT: 'pre-evaluation-report',
  EVALUATION_REPORT: 'evaluation-report',
  ADJUDICATION_REPORT: 'adjudication-report',
  TENDER_REGISTER: 'tender-register',
  PRE_COMMENCEMENT: 'pre-commencement',
  SITE_HANDOVER_MINUTES: 'site-handover-minutes',
  SURETY_GUARANTEE: 'surety-guarantee',
  INSURANCE_OF_WORKS: 'insurance-of-works',
  PROGRAMME_OF_WORKS: 'programme-of-works',
  KEY_PERSONNEL_REGISTER: 'key-personnel-register',
  SAFETY_FILE_AUDIT_REPORT: 'safety-file-audit-report',
  MONTHLY_CASH_FLOW: 'monthly-cash-flow',
  PROGRESS_REPORT: 'progress-report',
  SAFETY_REPORT: 'safety-report',
  PAYMENT_CERTIFICATE: 'payment-certificate',
  MEETING_MINUTES: 'meeting-minutes',
  VARIATION_CERTIFICATE: 'variation-certificate',
  EXTENSION_OF_TIME: 'extension-of-time',
  PRACTICAL_COMPLETION: 'practical-completion',
  DEFECTS_LIST: 'defects-list',
  COMPLETION_CERTIFICATE: 'completion-certificate',
  FINAL_ACCOUNT: 'final-account',
  AS_BUILT_DRAWING: 'as-built-drawing',
  FINAL_APPROVAL: 'final-approval',
  PROOF_OF_PAYMENT: 'proof-of-payment',
  OM_MANUAL: 'om-manual',
  CLOSE_OUT_REPORT: 'close-out-report',
  FINAL_COMPLETION: 'final-completion',
  SITE_IMAGE: 'site-image',
  DRONE_VIDEO: 'drone-video',
  ACTIVITY_IMAGE: 'activity-image',
  DIGITAL_SURVEY: 'digital-survey',
  GEOTECHNICAL: 'geotechnical',
  ENVIRONMENTAL: 'environmental',
  SOCIAL_FACILITATION: 'social-facilitation',
  COMMUNITY_MINUTES: 'community-minutes',
  OTHER: 'other',
};

const STAGE_DOCUMENT_MAP = {
  1: ['scoping-report'],
  2: ['preliminary-design-report', 'preliminary-design', 'preliminary-cost-estimate', 'digital-survey', 'geotechnical', 'environmental', 'social-facilitation', 'community-minutes'],
  3: ['detailed-design-report', 'detailed-design', 'detailed-cost-estimate'],
  4: ['tender-document', 'tender-evaluation', 'tender-drawing', 'appointment-letter'],
  5: [],
  6: ['appointment-letter'],
  7: ['payment-certificate', 'progress-report', 'safety-report', 'monthly-cash-flow', 'meeting-minutes'],
  8: ['practical-completion', 'defects-list'],
  9: ['final-approval', 'proof-of-payment', 'final-account', 'as-built-drawing', 'om-manual'],
};

const APPROVAL_REQUIRED_CATEGORIES = [
  'scoping-report',
  'preliminary-design-report',
  'detailed-design-report',
  'tender-document',
  'tender-evaluation',
  'appointment-letter',
  'payment-certificate',
  'variation-certificate',
  'practical-completion',
  'final-approval',
  'proof-of-payment',
];

module.exports = {
  FILE_CATEGORIES,
  STAGE_DOCUMENT_MAP,
  APPROVAL_REQUIRED_CATEGORIES,
};
