const ROLES = {
  SUPER_ADMIN: 'SUPER_ADMIN',
  ORG_ADMIN: 'ORG_ADMIN',
  DEPT_ADMIN: 'DEPT_ADMIN',
  PM: 'PM',
  MEMBER: 'MEMBER',
  CLIENT_APPROVER: 'CLIENT_APPROVER',
  VIEWER: 'VIEWER',
  CLIENT_TEMP: 'CLIENT_TEMP',
};

const PERMANENT_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ORG_ADMIN,
  ROLES.DEPT_ADMIN,
  ROLES.PM,
  ROLES.MEMBER,
  ROLES.CLIENT_APPROVER,
  ROLES.VIEWER,
];

const WRITER_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ORG_ADMIN,
  ROLES.DEPT_ADMIN,
  ROLES.PM,
];

const ADMIN_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ORG_ADMIN,
];

const APPROVER_ROLES = [
  ROLES.CLIENT_APPROVER,
  ROLES.DEPT_ADMIN,
  ROLES.ORG_ADMIN,
];

/** Client-side approvers for procurement trail steps (v9 two-party model; PM must not self-approve). */
const PROCUREMENT_STEP_REVIEW_ROLES = [
  ROLES.SUPER_ADMIN,
  ROLES.ORG_ADMIN,
  ROLES.DEPT_ADMIN,
  ROLES.CLIENT_APPROVER,
];

module.exports = {
  ROLES,
  PERMANENT_ROLES,
  WRITER_ROLES,
  ADMIN_ROLES,
  APPROVER_ROLES,
  PROCUREMENT_STEP_REVIEW_ROLES,
};
